config/routes.rb
Rails.application.routes.draw do
  get 'perfil/index'
  devise_for :users
  resources :tags
  resources :articles
  root 'home#index'
  get "/produtos/busca" => "produtos#busca", as: :busca_produto
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<% #Navbar %> 
  <nav class="navbar navbar-expand-lg navbar-light bg-light " id = "NavBar">

  <%= link_to 'Nuntium', root_path, class: "navbar-brand mr-auto font-weight-bold"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupprtedContent">
    <% if !user_signed_in? %>
    <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Log In
      </a>
      
      <div class="dropdown-menu dropdown-menu-right">
        <form class="px-4 py-3">
          <%= link_to 'Log in', new_user_session_path, class: "dropdown-item"%>
          <%= link_to 'Sign up', new_user_registration_path, class: "dropdown-item"%>
          </form>
            <% else %>
            <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%=current_user.name %>
          </a>
          
          <div class="dropdown-menu dropdown-menu-right">
            <form class="px-4 py-3">
              <%= link_to 'Profile', perfil_index_path, class: "dropdown-item" %>
              <%= link_to 'New article', new_article_path, class: "dropdown-item" %>
              <%= link_to 'Logout' , destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </form>
              
          </div>
          <% end %>


        </li>
      </ul>

      

    </div>
  </nav>
  <% #Fim Navbar %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


  <head>
    <title>Nuntium</title>
    <link rel="stylesheet" type="text/css" href="CSSReset.css" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif:400,400i,700" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "home" %>
    <%= stylesheet_link_tag "application" %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
    <script src="https:S//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <%= stylesheet_link_tag "articles" %>
    <%= stylesheet_link_tag "home" %>
    <%= stylesheet_link_tag "perfil" %>
    <%= stylesheet_link_tag "tags" %>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  

  <body class="text back">
  <%= render 'layouts/navbar', class: "font"  %>
    <%= yield %>
    <%= render 'layouts/navbar', class: "font"  %>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nuntium" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "home" %>
    <%= stylesheet_link_tag "application" %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body >

  <div class="font text ">
  <%= render 'layouts/navbar' %>
</div>
  <% #HomePage %>
  <div class= "container .h3 text " style = "padding-top: 5em">
    <div>
      <h1 class="font-weight-bold">Whats New?</h1>
      <hr></hr>
    </div>

      <% #Artigos Pequenos %>
      <div id = "SmallTrendingArea">
      <% @home.each do |article| %>

        <div id = "SmallTrending">
          <%= link_to article_path(article) do %>
          <div class="card bg-dark text-white" id= "">
            <%= image_tag article.photo.url(:medium), id: "ImagemCardSmall" %>
            <div class="card-img-overlay" id ="CardOverlay">
              <h5 class="card-title"><%= article.title %></h5>
              <p class="card-text"><%= article.description%></p>
            </div>
          </div>

        </div>
        
        <% end %>
      
      <% end %>
      </div>

      

      
      </div>
      <% #Fim Artigos Pequenos %>
      
    <div class = "container .h3 text ">
      <h1 class="font-weight-bold">Tags</h1>
      <hr></hr>
    </div>

    <div class="container">

<div class="row">
    <% @tag.each do |tag| %>
      <div class="col-3">
      <%= link_to tag_path(tag) do %>
      <div class="card bg-dark text-white " id = "Tag">
      <%= image_tag tag.avatar.url, id: "ImagemCardSmall" %>
        
        <div class="card-img-overlay" id = "TagName">
          <h1 class="card-title text" id = "TagText" ><%= tag.name%></h1>
        </div>
        </div>
      </div> 
      
      <% end %>
      
      <% end %>
</div>
     
    </div> 
    <% #Fim Tags %>


  </div>
  </div>



  </body>
</html>